version: '3'
services:
  app:
    container_name: finhub_app
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - finhub-postgres
    networks:
      - finhub


  finhub-postgres:
    image: postgres:latest
    container_name: finhub_db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - finhub

  migrate:
    image: migrate/migrate
    networks:
      - finhub
    volumes:
      - ./db/migration:/db/migration
    command: [ "-path", "/db/migration", "-database",  "postgresql://test:password@finhub-postgres:5432/finhub?sslmode=disable", "up"]
    depends_on:
      - finhub-postgres
    links:
      - finhub-postgres

volumes:
  api:
  database_postgres:

networks:
  finhub:
    driver: bridge